// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppGSL.h>
#include <Rcpp.h>

using namespace Rcpp;

// run_usdos
int run_usdos(std::string cfile, bool gen_shipment_network);
RcppExport SEXP _usdosr_run_usdos(SEXP cfileSEXP, SEXP gen_shipment_networkSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type cfile(cfileSEXP);
    Rcpp::traits::input_parameter< bool >::type gen_shipment_network(gen_shipment_networkSEXP);
    rcpp_result_gen = Rcpp::wrap(run_usdos(cfile, gen_shipment_network));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_usdosr_run_usdos", (DL_FUNC) &_usdosr_run_usdos, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_usdosr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
