# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Runs USDOS model for a given config file.
#'
#' @param cfile The name of the config file to use
#' @param gen_shipment_network Logical indicating whether you want to just generate shipments, defaults to FALSE
#' @return writes output to file specified in cfile
#' @examples
#' run_usdos("config.txt")
run_usdos <- function(cfile, gen_shipment_network = FALSE) {
    .Call('_usdosr_run_usdos', PACKAGE = 'usdosr', cfile, gen_shipment_network)
}

