# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Runs USDOS model for a given config file.
#' 
#' @param cfile the name of the config file to use
#' @return writes output to file
run_usdos <- function(cfile) {
    .Call('usdosr_run_usdos', PACKAGE = 'usdosr', cfile)
}

